Repository sensu-plugins/sensu-plugins-elasticsearch, pull requests merged in 2018-02, with the labels that each got.

#110 Don't try to fetch percolator metrics on ES 5+
  CHANGELOG.md
  bin/metrics-es-cluster.rb
Labels: Status: Needs Review, Type: Bug

#109 updated check-es-node-status.rb to check the status of all the nodes,…
  CHANGELOG.md
  bin/check-es-node-status.rb
Labels: Type: Enhancement

#101 adding cert option to some checks and metrics
  Rakefile
  bin/check-es-circuit-breakers.rb
  bin/check-es-cluster-status.rb
  bin/check-es-indices-sizes.rb
  bin/check-es-node-status.rb
  bin/metrics-es-cluster.rb
  bin/metrics-es-node-graphite.rb
  bin/metrics-es-node.rb
  sensu-plugins-elasticsearch.gemspec
Labels: Status: Needs Review, Type: Enhancement

#111 Allow sending headers to the elasticsearch client
  .gitignore
  .kitchen.yml
  .travis.yml
  CHANGELOG.md
  README.md
  Rakefile
  bin/check-es-query-average.rb
  bin/check-es-query-count.rb
  bin/check-es-query-exists.rb
  bin/check-es-query-ratio.rb
  lib/sensu-plugins-elasticsearch/elasticsearch-common.rb
  sensu-plugins-elasticsearch.gemspec
  test/fixtures/bootstrap.sh
  test/integration/helpers/serverspec/check-es-query-count-shared_spec.rb
  test/integration/helpers/serverspec/shared_spec.rb
  test/integration/helpers/serverspec/spec_helper.rb
  test/integration/ruby-20/serverspec/default_spec.rb
  test/integration/ruby-21/serverspec/default_spec.rb
  test/integration/ruby-22/serverspec/default_spec.rb
  test/integration/ruby-230/serverspec/default_spec.rb
  test/integration/ruby-241/serverspec/default_spec.rb
  test/spec_helper.rb
Labels: Status: Awaiting Response, Type: Enhancement
