Repository sensu-plugins/sensu-plugins-elasticsearch, pull requests merged in 2018-03, with the labels that each got.

#112 Add check-es-index-field-count.rb
  CHANGELOG.md
  README.md
  bin/check-es-indices-field-count.rb
  bin/check-es-indices-sizes.rb
  lib/sensu-plugins-elasticsearch/elasticsearch-query.rb
  sensu-plugins-elasticsearch.gemspec
  test/fixtures/bootstrap.sh
  test/integration/helpers/serverspec/check-es-indices-field-count-shared_spec.rb
Labels: Status: Awaiting Response, Type: Enhancement

#113 [CVE-2017-8418] - updating rubocop dependency.
  .rubocop.yml
  .travis.yml
  CHANGELOG.md
  Rakefile
  bin/check-es-heap.rb
  bin/check-es-indices-sizes.rb
  bin/check-es-shard-allocation-status.rb
  bin/metrics-es-cluster.rb
  bin/metrics-es-node-graphite.rb
  sensu-plugins-elasticsearch.gemspec
Labels: Impact: Breaking Change, Status: Needs Review, Type: Security

#114 [CVE-2017-17042] update vulnerable `yard` dependency
  CHANGELOG.md
  sensu-plugins-elasticsearch.gemspec
Labels: Type: Security
